export function makeDemoRuns() {
  const now = new Date();
  const ago = (ms: number) => new Date(Date.now() - ms);

  return [
    {
      type: "ping",
      target: "8.8.8.8",
      status: "success",
      startedAt: ago(5 * 60 * 1000),
      completedAt: ago(5 * 60 * 1000 - 1200),
      durationMs: 1200,
      demoMode: true,
      rawOutput: "PING 8.8.8.8: 56 data bytes\n4 packets transmitted, 4 received, 0% packet loss\nrtt min/avg/max/mdev = 10.123/14.456/18.789/3.123 ms",
      parsedResult: { summary: "4/4 packets received, avg 14.46ms", success: true, details: {} },
      metrics: { latencyMin: 10.123, latencyMax: 18.789, latencyAvg: 14.456, packetLoss: 0, jitter: 3.123, packetsTransmitted: 4, packetsReceived: 4, hopCount: null },
      hops: null,
      dnsRecords: null,
      error: null,
      parseWarnings: [],
      config: null,
    },
    {
      type: "traceroute",
      target: "google.com",
      status: "success",
      startedAt: ago(12 * 60 * 1000),
      completedAt: ago(12 * 60 * 1000 - 4500),
      durationMs: 4500,
      demoMode: true,
      rawOutput: "traceroute to google.com, 20 hops max",
      parsedResult: { summary: "5 hops traced", success: true, details: {} },
      metrics: { latencyMin: 1.1, latencyMax: 14.3, latencyAvg: 9.6, packetLoss: 0, jitter: null, packetsTransmitted: null, packetsReceived: null, hopCount: 5 },
      hops: [
        { hop: 1, host: "gateway.local", ip: "192.168.1.1", rtt1: 1.2, rtt2: 1.1, rtt3: 1.3, timeout: false },
        { hop: 2, host: "isp-edge.net", ip: "10.0.0.1", rtt1: 5.4, rtt2: 5.2, rtt3: 5.6, timeout: false },
        { hop: 3, host: "backbone-01.net", ip: "72.14.0.1", rtt1: 12.3, rtt2: 12.1, rtt3: 12.4, timeout: false },
        { hop: 4, host: null, ip: null, rtt1: null, rtt2: null, rtt3: null, timeout: true },
        { hop: 5, host: "google.com", ip: "142.250.80.46", rtt1: 14.2, rtt2: 14.1, rtt3: 14.3, timeout: false },
      ],
      dnsRecords: null,
      error: null,
      parseWarnings: [],
      config: null,
    },
    {
      type: "dns",
      target: "github.com",
      status: "success",
      startedAt: ago(20 * 60 * 1000),
      completedAt: ago(20 * 60 * 1000 - 230),
      durationMs: 230,
      demoMode: true,
      rawOutput: "; DNS query for github.com type A\n;; ANSWER SECTION:\ngithub.com.   60   IN   A   140.82.114.4",
      parsedResult: { summary: "1 record found", success: true, details: {} },
      metrics: { latencyMin: null, latencyMax: null, latencyAvg: null, packetLoss: null, jitter: null, packetsTransmitted: null, packetsReceived: null, hopCount: null },
      hops: null,
      dnsRecords: [{ type: "A", name: "github.com", value: "140.82.114.4", ttl: 60 }],
      error: null,
      parseWarnings: [],
      config: null,
    },
    {
      type: "port-check",
      target: "github.com",
      status: "success",
      startedAt: ago(25 * 60 * 1000),
      completedAt: ago(25 * 60 * 1000 - 180),
      durationMs: 180,
      demoMode: true,
      rawOutput: "Port check: github.com:443\nStatus: OPEN\nLatency: 42ms",
      parsedResult: { summary: "Port 443 is OPEN", success: true, details: { port: 443, open: true } },
      metrics: { latencyMin: null, latencyMax: null, latencyAvg: 42, packetLoss: null, jitter: null, packetsTransmitted: null, packetsReceived: null, hopCount: null },
      hops: null,
      dnsRecords: null,
      error: null,
      parseWarnings: [],
      config: null,
    },
    {
      type: "ping",
      target: "192.168.1.254",
      status: "failure",
      startedAt: ago(45 * 60 * 1000),
      completedAt: ago(45 * 60 * 1000 - 10000),
      durationMs: 10000,
      demoMode: true,
      rawOutput: "PING 192.168.1.254: 56 data bytes\n4 packets transmitted, 0 received, 100% packet loss",
      parsedResult: { summary: "All 4 packets lost", success: false, details: {} },
      metrics: { latencyMin: null, latencyMax: null, latencyAvg: null, packetLoss: 100, jitter: null, packetsTransmitted: 4, packetsReceived: 0, hopCount: null },
      hops: null,
      dnsRecords: null,
      error: "Host unreachable",
      parseWarnings: [],
      config: null,
    },
  ];
}

export function makeDemoProfiles() {
  return [
    {
      name: "Gaming Latency Check",
      description: "Check latency to popular gaming servers and DNS",
      category: "preset",
      targets: ["8.8.8.8", "1.1.1.1", "steam.com"],
      diagnostics: ["ping", "dns"],
      config: { count: 8 },
      isPreset: true,
    },
    {
      name: "DNS Issue Check",
      description: "Diagnose DNS resolution problems",
      category: "preset",
      targets: ["google.com", "cloudflare.com", "8.8.8.8"],
      diagnostics: ["dns", "ping"],
      config: { recordType: "A" },
      isPreset: true,
    },
    {
      name: "Office Network Quick Test",
      description: "Quick health check for office network connectivity",
      category: "preset",
      targets: ["8.8.8.8", "google.com"],
      diagnostics: ["ping", "traceroute", "dns"],
      config: {},
      isPreset: true,
    },
    {
      name: "Router Reachability",
      description: "Test gateway and local network reachability",
      category: "preset",
      targets: ["192.168.1.1", "10.0.0.1"],
      diagnostics: ["ping"],
      config: { count: 6 },
      isPreset: true,
    },
    {
      name: "Unreachable Host Investigation",
      description: "Trace and diagnose a host that seems unreachable",
      category: "preset",
      targets: ["target.example.com"],
      diagnostics: ["ping", "traceroute", "dns", "port-check"],
      config: {},
      isPreset: true,
    },
  ];
}
